name = "SphericalGeometry"
uuid = "b58e7a8d-b3e8-4a5d-bea9-e6440cab77fd"
authors = ["René Verbeek"]
version = "0.1.0"

[compat]
julia = "1.4.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
